# Track Types:

TRACK_TYPE_ROAD    = "ROAD"
TRACK_TYPE_WALKING = "WALKING"
TRACK_TYPE_BIKE    = "BIKE"
TRACK_TYPE_HORSE   = "HORSE"

# Track Directions:

TRACK_DIRECTION_BOTH     = "BOTH"
TRACK_DIRECTION_FORWARD  = "FORWARD"
TRACK_DIRECTION_BACKWARD = "BACKWARD"

# Track Status Values:

TRACK_STATUS_OPEN   = "OPEN"
TRACK_STATUS_CLOSED = "CLOSED"

ROAD_WIDTH  = 0.0001
TRAIL_WIDTH = 0.00003
POINT_SIZE  = 0.0004

